---
  - name: Install autossh
    apt:
      state: present
      name: autossh
    become: yes

  - name: Copy ssh config
    template:
      src: ssh_config.j2
      dest: ~/.ssh/config
    when: image_creation is undefined

  - name: Copy autossh service config
    template:
       src: autossh.service.j2
       dest: /etc/systemd/system/autossh.service
    become: yes
    when: image_creation is undefined

  - name: Reload systemctl
    command: systemctl daemon-reload
    become: yes
    when: image_creation is undefined

  - name: Add gateway as known host
    lineinfile:
      dest: ~/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item) }}"
      regexp: "{{'^' + item }}"
    with_items:
      - "{{ hostvars['gateway']['ansible_host'] }}"
    when: image_creation is undefined

  - name: Start autossh
    service:
      enabled: yes
      name: autossh
      state: restarted
    become: yes
    when: image_creation is undefined
