---
  - name: Install packages for python-ldap pip module
    apt:
      name: '{{ item }}'
    become: yes
    with_items: [ 'python-dev', 'python-pip' ]

  - name: Install sshuttle
    pip:
      name: sshuttle
      version: '{{ sshuttle_version }}'
    become: yes

  - name: Copy sshuttle service config
    template:
       src: sshuttle.service.j2
       dest: /etc/systemd/system/sshuttle.service
    become: yes
    when: image_creation is undefined

  - name: Reload systemctl
    command: systemctl daemon-reload
    become: yes
    when: image_creation is undefined

  - name: Add gateway as known host
    lineinfile:
      dest: ~/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item) }}"
      regexp: "{{'^' + item }}"
    with_items:
      - "{{ hostvars['gateway']['ansible_host'] }}"
    when: image_creation is undefined

  - name: Start sshuttle
    service:
      enabled: yes
      name: sshuttle
      state: restarted
    become: yes
    when: image_creation is undefined
